### ISSUE TITLE
usertest无法通过

### ISSUE THREAD

**Issue by cfkka** [relaxcn/xv6-labs-2022-solutions#1]
你好。经过学习，这一份代码无法通过usertest只能通过cowtest，请问这是正常的吗？谢谢。
<img width="1537" alt="image" src="https://github.com/relaxcn/xv6-labs-2022-solutions/assets/169071513/300dd8e4-e3ac-4cc2-b2f4-82a739b135de">

**Comment by cfkka** [comment]
cow分支

**Comment by relaxcn** [comment]
你好，你可以clone这个仓库，切换到 cow 分支进行测试。经过我的测试是没问题的。
或许教程中的有所遗漏，你可以从git记录中查找相关修改。
![image](https://github.com/relaxcn/xv6-labs-2022-solutions/assets/64476349/d4999956-6e34-4b80-a8df-4a0b529e4f7e)

**Comment by cfkka** [comment]
好的谢谢
